exports.obj = {
  GROUPID: 'GROUPID', // 群ID
  GROUPNAME: 'GROUPNAME', // 群名字
  GROUPREMARK: 'GROUPREMARK', // 群公告
  CREATEUSERID: 'CREATEUSERID', // 创建人ID
  CREATETIME: 'CREATETIME', // 创建时间
  DISSOLUTIONTIME: 'DISSOLUTIONTIME', //解散时间
  GROUPSTATE: 'GROUPSTATE', // 群状态 0 正常 | 1 解散
  TS: 'TS' // 时间戳
};
